exchanges:
  - exchange: BINANCE
    enabled: true
    symbols:
      - BTCUSDT
      - ETHUSDT
    data_types:
      - TICKER
      - TRADES
      - ORDER_BOOK

aeron:
  stream_directory: /tmp/aeron-data
